name = "empty-variable-in-wrangler"
main = "src/index.ts"
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat"]

[env.stg]
d1_databases = [
  { binding = "DB", database_name = "db-stg", database_id = <stg-db-id> },
]

[env]
d1_databases = [
  { binding = "DB", database_name = "db", database_id = <prd-db-id> },
]

[[d1_databases]]
binding = "DB"
database_name = "db-stg"
database_id = <stg-db-id>

[[d1_databases]]
binding = "DB"
database_name = "db"
database_id = <prd-db-id>
